FROM node:lts-alpine

ENV PORT 5000

# create & set working directory
RUN mkdir -p /usr/src
WORKDIR /usr/src

# copy source files
COPY . /usr/src

# install dependencies
RUN npm ci

# start app
RUN npm run build
EXPOSE 5000
CMD npm run start